services:
  skin-analyzer-grpc:
    build:
      context: ./skin-analyzer-service
      dockerfile: Dockerfile
    ports:
      - "8008:8008"  # gRPC port
    networks:
      - inference-network-grpc
    environment:
      - "DB_HOST=database_grpc"
      - "DB_USER=serverdata"
      - "DB_PASSWORD=server123"
      - "DB_NAME=chronic"
      - "DB_PORT=5432"
      - "ONNX_MODEL_PATH="
      - "CLASS_DICTIONARY_PATH="
    depends_on:
      - database_grpc
    cpus: 5
    mem_limit: 5G

  skin-analyzer-rest:
    build:
      context: ./skin-analyzer-service
      dockerfile: Dockerfile
    ports:
      - "8088:8088"  # REST API port
    networks:
      - inference-network-rest
    environment:
      - "REST_MODE=true"
      - "DB_HOST=database_rest"
      - "DB_USER=serverdata"
      - "DB_PASSWORD=server123"
      - "DB_NAME=chronic"
      - "DB_PORT=5432"
      - "ONNX_MODEL_PATH="
      - "CLASS_DICTIONARY_PATH="
    depends_on:
      - database_rest
    cpus: 5
    mem_limit: 5G

  database_grpc:
    image: postgres:16-alpine
    networks:
      - inference-network-grpc
    environment:
      - POSTGRES_DB=chronic
      - POSTGRES_USER=serverdata
      - POSTGRES_PASSWORD=server123
    volumes:
      - db1:/var/lib/postgresql/data


  database_rest:
    image: postgres:16-alpine
    networks:
      - inference-network-rest
    environment:
      - POSTGRES_DB=chronic
      - POSTGRES_USER=serverdata
      - POSTGRES_PASSWORD=server123
    volumes:
      - db2:/var/lib/postgresql/data


networks:
  inference-network-grpc:
    driver: bridge

  inference-network-rest:
    driver: bridge


volumes:
  db1:
  db2:
