// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.7
// source: skin_analyzer.proto

package citra

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ImageType     string                 `protobuf:"bytes,2,opt,name=image_type,json=imageType,proto3" json:"image_type,omitempty"`
	ClientSha256  []byte                 `protobuf:"bytes,3,opt,name=client_sha256,json=clientSha256,proto3" json:"client_sha256,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_skin_analyzer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_skin_analyzer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_skin_analyzer_proto_rawDescGZIP(), []int{0}
}

func (x *ImageInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ImageInfo) GetImageType() string {
	if x != nil {
		return x.ImageType
	}
	return ""
}

func (x *ImageInfo) GetClientSha256() []byte {
	if x != nil {
		return x.ClientSha256
	}
	return nil
}

func (x *ImageInfo) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AnalyzeSkinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestPayload:
	//
	//	*AnalyzeSkinRequest_Info
	//	*AnalyzeSkinRequest_Chunk
	RequestPayload isAnalyzeSkinRequest_RequestPayload `protobuf_oneof:"request_payload"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeSkinRequest) Reset() {
	*x = AnalyzeSkinRequest{}
	mi := &file_skin_analyzer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeSkinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeSkinRequest) ProtoMessage() {}

func (x *AnalyzeSkinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_skin_analyzer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeSkinRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeSkinRequest) Descriptor() ([]byte, []int) {
	return file_skin_analyzer_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeSkinRequest) GetRequestPayload() isAnalyzeSkinRequest_RequestPayload {
	if x != nil {
		return x.RequestPayload
	}
	return nil
}

func (x *AnalyzeSkinRequest) GetInfo() *ImageInfo {
	if x != nil {
		if x, ok := x.RequestPayload.(*AnalyzeSkinRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *AnalyzeSkinRequest) GetChunk() []byte {
	if x != nil {
		if x, ok := x.RequestPayload.(*AnalyzeSkinRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isAnalyzeSkinRequest_RequestPayload interface {
	isAnalyzeSkinRequest_RequestPayload()
}

type AnalyzeSkinRequest_Info struct {
	Info *ImageInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type AnalyzeSkinRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*AnalyzeSkinRequest_Info) isAnalyzeSkinRequest_RequestPayload() {}

func (*AnalyzeSkinRequest_Chunk) isAnalyzeSkinRequest_RequestPayload() {}

type AnalysisResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Label          string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Confidence     float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Recommendation string                 `protobuf:"bytes,4,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalysisResult) Reset() {
	*x = AnalysisResult{}
	mi := &file_skin_analyzer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalysisResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalysisResult) ProtoMessage() {}

func (x *AnalysisResult) ProtoReflect() protoreflect.Message {
	mi := &file_skin_analyzer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalysisResult.ProtoReflect.Descriptor instead.
func (*AnalysisResult) Descriptor() ([]byte, []int) {
	return file_skin_analyzer_proto_rawDescGZIP(), []int{2}
}

func (x *AnalysisResult) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AnalysisResult) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalysisResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnalysisResult) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

type AnalyzeSkinResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AnalysisId        string                 `protobuf:"bytes,1,opt,name=analysis_id,json=analysisId,proto3" json:"analysis_id,omitempty"`
	AnalysisTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=analysis_timestamp,json=analysisTimestamp,proto3" json:"analysis_timestamp,omitempty"`
	ServerSha256      []byte                 `protobuf:"bytes,4,opt,name=server_sha256,json=serverSha256,proto3" json:"server_sha256,omitempty"`
	Results           []*AnalysisResult      `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AnalyzeSkinResponse) Reset() {
	*x = AnalyzeSkinResponse{}
	mi := &file_skin_analyzer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeSkinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeSkinResponse) ProtoMessage() {}

func (x *AnalyzeSkinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_skin_analyzer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeSkinResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeSkinResponse) Descriptor() ([]byte, []int) {
	return file_skin_analyzer_proto_rawDescGZIP(), []int{3}
}

func (x *AnalyzeSkinResponse) GetAnalysisId() string {
	if x != nil {
		return x.AnalysisId
	}
	return ""
}

func (x *AnalyzeSkinResponse) GetAnalysisTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.AnalysisTimestamp
	}
	return nil
}

func (x *AnalyzeSkinResponse) GetServerSha256() []byte {
	if x != nil {
		return x.ServerSha256
	}
	return nil
}

func (x *AnalyzeSkinResponse) GetResults() []*AnalysisResult {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_skin_analyzer_proto protoreflect.FileDescriptor

const file_skin_analyzer_proto_rawDesc = "" +
	"\n" +
	"\x13skin_analyzer.proto\x12\rskin_analyzer\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x01\n" +
	"\tImageInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"image_type\x18\x02 \x01(\tR\timageType\x12#\n" +
	"\rclient_sha256\x18\x03 \x01(\fR\fclientSha256\x12B\n" +
	"\bmetadata\x18\x04 \x03(\v2&.skin_analyzer.ImageInfo.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x12AnalyzeSkinRequest\x12.\n" +
	"\x04info\x18\x01 \x01(\v2\x18.skin_analyzer.ImageInfoH\x00R\x04info\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x11\n" +
	"\x0frequest_payload\"\x90\x01\n" +
	"\x0eAnalysisResult\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12&\n" +
	"\x0erecommendation\x18\x04 \x01(\tR\x0erecommendation\"\xdf\x01\n" +
	"\x13AnalyzeSkinResponse\x12\x1f\n" +
	"\vanalysis_id\x18\x01 \x01(\tR\n" +
	"analysisId\x12I\n" +
	"\x12analysis_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x11analysisTimestamp\x12#\n" +
	"\rserver_sha256\x18\x04 \x01(\fR\fserverSha256\x127\n" +
	"\aresults\x18\x05 \x03(\v2\x1d.skin_analyzer.AnalysisResultR\aresults2m\n" +
	"\x13SkinAnalysisService\x12V\n" +
	"\vAnalyzeSkin\x12!.skin_analyzer.AnalyzeSkinRequest\x1a\".skin_analyzer.AnalyzeSkinResponse(\x01B!Z\x1fskin-analyzer-service/gen;citrab\x06proto3"

var (
	file_skin_analyzer_proto_rawDescOnce sync.Once
	file_skin_analyzer_proto_rawDescData []byte
)

func file_skin_analyzer_proto_rawDescGZIP() []byte {
	file_skin_analyzer_proto_rawDescOnce.Do(func() {
		file_skin_analyzer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_skin_analyzer_proto_rawDesc), len(file_skin_analyzer_proto_rawDesc)))
	})
	return file_skin_analyzer_proto_rawDescData
}

var file_skin_analyzer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_skin_analyzer_proto_goTypes = []any{
	(*ImageInfo)(nil),             // 0: skin_analyzer.ImageInfo
	(*AnalyzeSkinRequest)(nil),    // 1: skin_analyzer.AnalyzeSkinRequest
	(*AnalysisResult)(nil),        // 2: skin_analyzer.AnalysisResult
	(*AnalyzeSkinResponse)(nil),   // 3: skin_analyzer.AnalyzeSkinResponse
	nil,                           // 4: skin_analyzer.ImageInfo.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_skin_analyzer_proto_depIdxs = []int32{
	4, // 0: skin_analyzer.ImageInfo.metadata:type_name -> skin_analyzer.ImageInfo.MetadataEntry
	0, // 1: skin_analyzer.AnalyzeSkinRequest.info:type_name -> skin_analyzer.ImageInfo
	5, // 2: skin_analyzer.AnalyzeSkinResponse.analysis_timestamp:type_name -> google.protobuf.Timestamp
	2, // 3: skin_analyzer.AnalyzeSkinResponse.results:type_name -> skin_analyzer.AnalysisResult
	1, // 4: skin_analyzer.SkinAnalysisService.AnalyzeSkin:input_type -> skin_analyzer.AnalyzeSkinRequest
	3, // 5: skin_analyzer.SkinAnalysisService.AnalyzeSkin:output_type -> skin_analyzer.AnalyzeSkinResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_skin_analyzer_proto_init() }
func file_skin_analyzer_proto_init() {
	if File_skin_analyzer_proto != nil {
		return
	}
	file_skin_analyzer_proto_msgTypes[1].OneofWrappers = []any{
		(*AnalyzeSkinRequest_Info)(nil),
		(*AnalyzeSkinRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_skin_analyzer_proto_rawDesc), len(file_skin_analyzer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_skin_analyzer_proto_goTypes,
		DependencyIndexes: file_skin_analyzer_proto_depIdxs,
		MessageInfos:      file_skin_analyzer_proto_msgTypes,
	}.Build()
	File_skin_analyzer_proto = out.File
	file_skin_analyzer_proto_goTypes = nil
	file_skin_analyzer_proto_depIdxs = nil
}
