# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import skin_analyzer_pb2 as skin__analyzer__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in skin_analyzer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SkinAnalysisServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeSkin = channel.stream_unary(
                '/skin_analyzer.SkinAnalysisService/AnalyzeSkin',
                request_serializer=skin__analyzer__pb2.AnalyzeSkinRequest.SerializeToString,
                response_deserializer=skin__analyzer__pb2.AnalyzeSkinResponse.FromString,
                _registered_method=True)


class SkinAnalysisServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeSkin(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SkinAnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeSkin': grpc.stream_unary_rpc_method_handler(
                    servicer.AnalyzeSkin,
                    request_deserializer=skin__analyzer__pb2.AnalyzeSkinRequest.FromString,
                    response_serializer=skin__analyzer__pb2.AnalyzeSkinResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'skin_analyzer.SkinAnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('skin_analyzer.SkinAnalysisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SkinAnalysisService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeSkin(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/skin_analyzer.SkinAnalysisService/AnalyzeSkin',
            skin__analyzer__pb2.AnalyzeSkinRequest.SerializeToString,
            skin__analyzer__pb2.AnalyzeSkinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
