# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: skin_analyzer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'skin_analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13skin_analyzer.proto\x12\rskin_analyzer\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb2\x01\n\tImageInfo\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nimage_type\x18\x02 \x01(\t\x12\x15\n\rclient_sha256\x18\x03 \x01(\x0c\x12\x38\n\x08metadata\x18\x04 \x03(\x0b\x32&.skin_analyzer.ImageInfo.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"b\n\x12\x41nalyzeSkinRequest\x12(\n\x04info\x18\x01 \x01(\x0b\x32\x18.skin_analyzer.ImageInfoH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\x11\n\x0frequest_payload\"`\n\x0e\x41nalysisResult\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x16\n\x0erecommendation\x18\x04 \x01(\t\"\xa9\x01\n\x13\x41nalyzeSkinResponse\x12\x13\n\x0b\x61nalysis_id\x18\x01 \x01(\t\x12\x36\n\x12\x61nalysis_timestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rserver_sha256\x18\x04 \x01(\x0c\x12.\n\x07results\x18\x05 \x03(\x0b\x32\x1d.skin_analyzer.AnalysisResult2m\n\x13SkinAnalysisService\x12V\n\x0b\x41nalyzeSkin\x12!.skin_analyzer.AnalyzeSkinRequest\x1a\".skin_analyzer.AnalyzeSkinResponse(\x01\x42!Z\x1fskin-analyzer-service/gen;citrab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'skin_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\037skin-analyzer-service/gen;citra'
  _globals['_IMAGEINFO_METADATAENTRY']._loaded_options = None
  _globals['_IMAGEINFO_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_IMAGEINFO']._serialized_start=72
  _globals['_IMAGEINFO']._serialized_end=250
  _globals['_IMAGEINFO_METADATAENTRY']._serialized_start=203
  _globals['_IMAGEINFO_METADATAENTRY']._serialized_end=250
  _globals['_ANALYZESKINREQUEST']._serialized_start=252
  _globals['_ANALYZESKINREQUEST']._serialized_end=350
  _globals['_ANALYSISRESULT']._serialized_start=352
  _globals['_ANALYSISRESULT']._serialized_end=448
  _globals['_ANALYZESKINRESPONSE']._serialized_start=451
  _globals['_ANALYZESKINRESPONSE']._serialized_end=620
  _globals['_SKINANALYSISSERVICE']._serialized_start=622
  _globals['_SKINANALYSISSERVICE']._serialized_end=731
# @@protoc_insertion_point(module_scope)
